### ISSUE TITLE
Cannot save tags

### ISSUE THREAD

**Issue by thomasklemm** [bradphelan/rocket_tag#10]
Rocket_tag sometimes will not save changes to tags (or am I not adding tags the right way?).

My stack: Rails 3.2.3 running on top of Ruby 1.9.3-p125

Suggestions anyone?

```
irb(main):001:0> r1 = Repo.first
  Repo Load (0.3ms)  SELECT "repos".* FROM "repos" LIMIT 1
  RocketTag::Tagging Load (0.4ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" IN (1)
  RocketTag::Tag Load (0.2ms)  SELECT "tags".* FROM "tags" WHERE "tags"."id" IN (2, 3, 4)
=> #<Repo id: 1, name: "foundation", owner: "zurb", description: "An easy to use, powerful, and flexible framework fo...", watchers: 3639, forks: 424, github_url: "https://github.com/zurb/foundation", homepage: "http://foundation.zurb.com", last_updated: "2012-04-21 11:45:59", created_at: "2012-04-21 12:56:54", updated_at: "2012-04-21 19:08:37", wiki_text: "Foundation is the most awesome design framework one...">
irb(main):002:0> r1.languages
=> ["kiting", "surfing"]
irb(main):003:0> r1.languages << "coding"
=> ["kiting", "surfing", "coding"]
irb(main):004:0> r1.save
   (0.1ms)  begin transaction
   (0.1ms)  commit transaction
=> true
irb(main):005:0> r2 = Repo.first
  Repo Load (0.3ms)  SELECT "repos".* FROM "repos" LIMIT 1
  RocketTag::Tagging Load (0.3ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" IN (1)
  RocketTag::Tag Load (0.3ms)  SELECT "tags".* FROM "tags" WHERE "tags"."id" IN (2, 3, 4)
=> #<Repo id: 1, name: "foundation", owner: "zurb", description: "An easy to use, powerful, and flexible framework fo...", watchers: 3639, forks: 424, github_url: "https://github.com/zurb/foundation", homepage: "http://foundation.zurb.com", last_updated: "2012-04-21 11:45:59", created_at: "2012-04-21 12:56:54", updated_at: "2012-04-21 19:08:37", wiki_text: "Foundation is the most awesome design framework one...">
irb(main):006:0> r2.languages
=> ["kiting", "surfing"]
irb(main):007:0> 
```

**Comment by thomasklemm** [comment]
Temporary workaround: Using model.update_attribute("tag_name", ["array", "of", "tag", "values"]) seems to work properly.

```
Loading development environment (Rails 3.2.3)
irb(main):001:0> r = Repo.first
  Repo Load (0.3ms)  SELECT "repos".* FROM "repos" LIMIT 1
  RocketTag::Tagging Load (0.3ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" IN (1)
  RocketTag::Tag Load (0.2ms)  SELECT "tags".* FROM "tags" WHERE "tags"."id" IN (2)
=> #<Repo id: 1, name: "foundation", owner: "zurb", description: "An easy to use, powerful, and flexible framework fo...", watchers: 3639, forks: 424, github_url: "https://github.com/zurb/foundation", homepage: "http://foundation.zurb.com", last_updated: "2012-04-21 11:45:59", created_at: "2012-04-21 12:56:54", updated_at: "2012-04-22 10:58:20", wiki_text: "Foundation is the most awesome design framework one...">
irb(main):002:0> r.languages
=> []
irb(main):003:0> langs = ["ruby", "javascript", "scala"]
=> ["ruby", "javascript", "scala"]
---
[...]
---
irb(main):005:0> r.update_attribute("languages", langs)
   (0.1ms)  begin transaction
  SQL (0.2ms)  DELETE FROM "taggings" WHERE "taggings"."taggable_id" = 1 AND "taggings"."taggable_type" = 'Repo' AND "taggings"."context" = 'languages'
  RocketTag::Tag Load (0.2ms)  SELECT "tags".* FROM "tags" WHERE "tags"."name" IN ('ruby', 'javascript', 'scala')
  RocketTag::Tag Exists (0.1ms)  SELECT 1 FROM "tags" WHERE "tags"."name" = 'javascript' LIMIT 1
  SQL (0.6ms)  INSERT INTO "tags" ("name") VALUES (?)  [["name", "javascript"]]
  RocketTag::Tag Exists (0.1ms)  SELECT 1 FROM "tags" WHERE "tags"."name" = 'scala' LIMIT 1
  SQL (0.1ms)  INSERT INTO "tags" ("name") VALUES (?)  [["name", "scala"]]
  RocketTag::Tagging Exists (0.2ms)  SELECT 1 FROM "taggings" WHERE ("taggings"."tag_id" = 1 AND "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" = 1 AND "taggings"."context" = 'languages' AND "taggings"."tagger_id" IS NULL AND "taggings"."tagger_type" IS NULL) LIMIT 1
  SQL (2.0ms)  INSERT INTO "taggings" ("context", "created_at", "tag_id", "taggable_id", "taggable_type", "tagger_id", "tagger_type") VALUES (?, ?, ?, ?, ?, ?, ?)  [["context", :languages], ["created_at", Sun, 22 Apr 2012 15:28:02 UTC +00:00], ["tag_id", 1], ["taggable_id", 1], ["taggable_type", "Repo"], ["tagger_id", nil], ["tagger_type", nil]]
  RocketTag::Tagging Exists (0.2ms)  SELECT 1 FROM "taggings" WHERE ("taggings"."tag_id" = 9 AND "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" = 1 AND "taggings"."context" = 'languages' AND "taggings"."tagger_id" IS NULL AND "taggings"."tagger_type" IS NULL) LIMIT 1
  SQL (0.2ms)  INSERT INTO "taggings" ("context", "created_at", "tag_id", "taggable_id", "taggable_type", "tagger_id", "tagger_type") VALUES (?, ?, ?, ?, ?, ?, ?)  [["context", :languages], ["created_at", Sun, 22 Apr 2012 15:28:02 UTC +00:00], ["tag_id", 9], ["taggable_id", 1], ["taggable_type", "Repo"], ["tagger_id", nil], ["tagger_type", nil]]
  RocketTag::Tagging Exists (0.1ms)  SELECT 1 FROM "taggings" WHERE ("taggings"."tag_id" = 10 AND "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" = 1 AND "taggings"."context" = 'languages' AND "taggings"."tagger_id" IS NULL AND "taggings"."tagger_type" IS NULL) LIMIT 1
  SQL (0.1ms)  INSERT INTO "taggings" ("context", "created_at", "tag_id", "taggable_id", "taggable_type", "tagger_id", "tagger_type") VALUES (?, ?, ?, ?, ?, ?, ?)  [["context", :languages], ["created_at", Sun, 22 Apr 2012 15:28:02 UTC +00:00], ["tag_id", 10], ["taggable_id", 1], ["taggable_type", "Repo"], ["tagger_id", nil], ["tagger_type", nil]]
   (19.4ms)  commit transaction
=> true
irb(main):006:0> r2 = Repo.first
  Repo Load (0.3ms)  SELECT "repos".* FROM "repos" LIMIT 1
  RocketTag::Tagging Load (0.3ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_type" = 'Repo' AND "taggings"."taggable_id" IN (1)
  RocketTag::Tag Load (0.3ms)  SELECT "tags".* FROM "tags" WHERE "tags"."id" IN (2, 1, 9, 10)
=> #<Repo id: 1, name: "foundation", owner: "zurb", description: "An easy to use, powerful, and flexible framework fo...", watchers: 3639, forks: 424, github_url: "https://github.com/zurb/foundation", homepage: "http://foundation.zurb.com", last_updated: "2012-04-21 11:45:59", created_at: "2012-04-21 12:56:54", updated_at: "2012-04-22 10:58:20", wiki_text: "Foundation is the most awesome design framework one...">
irb(main):007:0> r2.languages
=> ["ruby", "javascript", "scala"]

```

Note that this method skips validations!

**Comment by part-timer** [comment]
I also experienced this ;-)

The mystery seams to be in lib/rocket_tag/taggable.rb#266 et sqq.
the method #{context} don't write the tags as #{context}= do ...

My temporary solution was to use something like:

``` ruby
modelWithTagsInstance.tag_context= modelWithTagsInstance.tag_context << 'new Tag'
```

But your solution with update_attribute is elegant indeed ... will give it a try when reviewing my code.

Another way could be to patch rocket_tag by adding a new method #{context}<< - if this is actually possible in ruby!?!
I'm to new to ruby, so i hesitate ... ;-)

**Comment by garethrees** [comment]
I get a similar problem:

```
1.9.2-p290 :002 > user.skills
 => [] 
1.9.2-p290 :003 > user.skills = ["Ruby", "Rails"]
 => ["Ruby", "Rails"] 
1.9.2-p290 :004 > user.save
   (0.3ms)  BEGIN
  SQL (0.8ms)  DELETE FROM `taggings` WHERE `taggings`.`taggable_id` = 1 AND `taggings`.`taggable_type` = 'User' AND `taggings`.`context` = `taggings`.`skills`
   (0.2ms)  ROLLBACK
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'taggings.skills' in 'where clause': DELETE FROM `taggings` WHERE `taggings`.`taggable_id` = 1 AND `taggings`.`taggable_type` = 'User' AND `taggings`.`context` = `taggings`.`skills`
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `block in execute'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activesupport-3.2.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:238:in `exec_delete'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:101:in `delete'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `delete'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/relation.rb:411:in `delete_all'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/rocket_tag-0.3.1/lib/rocket_tag/taggable.rb:51:in `destroy_tags_for_context'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/rocket_tag-0.3.1/lib/rocket_tag/taggable.rb:202:in `block (3 levels) in setup_for_rocket_tag'
    from /Users/gareth/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/set.rb:222:in `block in each'
    from /Users/gareth/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/set.rb:222:in `each_key'
    from /Users/gareth/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/set.rb:222:in `each'
... 7 levels...
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/validations.rb:50:in `save'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:241:in `block in save'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.2.2/lib/active_record/transactions.rb:240:in `save'
    from (irb):4
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.2/lib/rails/commands/console.rb:47:in `start'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.2/lib/rails/commands/console.rb:8:in `start'
    from /Users/gareth/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.2.2/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'1.9.2-p290 :005 > 
```

**Comment by bradphelan** [comment]
I've cleaned out what I think is the source of all these problems and I've pushed 0.5.0 to rubygems. Reopen if there is still this issue.

**Comment by thomasklemm** [comment]
Thanks a lot. I'll have a try.
