### ISSUE TITLE
Getting SQL error with popular_tags on model

### ISSUE THREAD

**Issue by walterdavis** [bradphelan/rocket_tag#25]
Trying this in Console, I get a big long error related to SQL:

```
1.9.2p320 :001 > Page.popular_tags
  RocketTag::Tag Load (0.3ms)  SELECT `tags`.* FROM (SELECT count(`tags`.`id`) AS tags_count, * FROM `tags` INNER JOIN `taggings` ON `taggings`.`tag_id` = `tags`.`id` WHERE `taggings`.`taggable_type` = 'Page' AND `taggings`.`taggable_id` IN (SELECT `pages`.`id` FROM `pages` ) GROUP BY `tags`.`id`, `tags`.`name`, taggings.id, tags.id ORDER BY tags_count desc) tags 
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* FROM `tags` INNER JOIN `taggings` ON `taggings`.`tag_id` = `tags`.`id` WHERE `' at line 1: SELECT `tags`.* FROM (SELECT count(`tags`.`id`) AS tags_count, * FROM `tags` INNER JOIN `taggings` ON `taggings`.`tag_id` = `tags`.`id` WHERE `taggings`.`taggable_type` = 'Page' AND `taggings`.`taggable_id` IN (SELECT `pages`.`id` FROM `pages` ) GROUP BY `tags`.`id`, `tags`.`name`, taggings.id, tags.id ORDER BY tags_count desc) tags 
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `query'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `block in execute'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activesupport-3.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:243:in `execute'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:211:in `execute'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:215:in `exec_query'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/mysql2_adapter.rb:224:in `select'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/querying.rb:38:in `block in find_by_sql'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/explain.rb:40:in `logging_query_plan'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/querying.rb:37:in `find_by_sql'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/relation.rb:171:in `exec_queries'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/relation.rb:160:in `block in to_a'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/explain.rb:33:in `logging_query_plan'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/relation.rb:159:in `to_a'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/activerecord-3.2.6/lib/active_record/relation.rb:498:in `inspect'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in `start'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
    from /Users/waltd/.rvm/gems/ruby-1.9.2-p320/gems/railties-3.2.6/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
```

I've stared at it for a while, and I can't see what's wrong here. I'd just like to get a list of the currently used tags, in order of usage.

Thanks,

Walter

**Comment by walterdavis** [comment]
Fiddling around in Sequel Pro, I came up with this query, which works perfectly.

```
SELECT `tags`.*, count(`tags`.`id`) AS tags_count FROM `tags` INNER JOIN `taggings` ON `taggings`.`tag_id` = `tags`.`id` WHERE `taggings`.`taggable_type` = 'Page' AND `taggings`.`taggable_id` IN (SELECT `pages`.`id` FROM `pages` ) GROUP BY `tags`.`id`, `tags`.`name`, taggings.id, tags.id ORDER BY tags_count DESC
```

Now how do I get Squeel to create this instead of what it came up with?

**Comment by bradphelan** [comment]
I've made a few changes to the lib. Can you test the latest gem under mysql. I'm only testing sqlite and postgres at the moment
