### ISSUE TITLE
model.find_similar  not found

### ISSUE THREAD

**Issue by RussellSnow** [bradphelan/rocket_tag#4]
What am I doing wrong?

```
ruby-1.9.2-p290 :078 > b.hardware
 => ["ff", "dfg"] 
ruby-1.9.2-p290 :079 > b.class
 => Event(id: integer, name: string, description: text, created_at: datetime, updated_at: datetime) 
ruby-1.9.2-p290 :080 > b.hardware
 => ["ff", "dfg"] 
ruby-1.9.2-p290 :081 > b.find_similar
NoMethodError: undefined method `find_similar' for #<Event:0x8982774>
    from /home/russell/.rvm/gems/ruby-1.9.2-p290/gems/activemodel-3.1.3/lib/active_model/attribute_methods.rb:385:in `method_missing'
    from /home/russell/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.3/lib/active_record/attribute_methods.rb:60:in `method_missing'
    from (irb):81
    from /home/russell/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:45:in `start'
    from /home/russell/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands/console.rb:8:in `start'
    from /home/russell/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.3/lib/rails/commands.rb:40:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by part-timer** [comment]
Got the same thing here. Guess it's due to me stucked to rocket_tag v0.0.4, 'cause i'm stucked to rails v3.1 ... 
@bradphelan: Would be happy about a update of "Clean, modern and maintainable, context aware tagging library for rails 3.1 +" to "Clean, modern and maintainable, context aware tagging library for rails 3.**2** +" or/and a hint in the ReadMe if i'm right ... 
Thx in advance ;-)

**Comment by thomasklemm** [comment]
Same problem, using Rails 3.2

**Comment by thomasklemm** [comment]
Seems like the method has been renamed to `tagged_with`. Works for me.

**Comment by bradphelan** [comment]
Fixed in the referenced pull request
